<?php
ob_start();
require __DIR__ . '/TCPDF-main/tcpdf.php';
require __DIR__ . '/includes/db.php';

if (!isset($_GET['visit_id'])) {
    die("Invalid request.");
}

$visit_id = intval($_GET['visit_id']);
$res = $conn->query("
    SELECT v.*, vh.brand, vh.model, vh.year, vh.registration_no,
           u.name AS seller_name, u.email AS seller_email, u.phone AS seller_phone, u.address AS seller_address,
           b.name AS buyer_name, b.email AS buyer_email
    FROM visits v
    JOIN inquiries i ON v.inquiry_id = i.id
    JOIN vehicles vh ON i.vehicle_id = vh.id
    JOIN users u ON vh.user_id = u.id
    JOIN users b ON v.buyer_id = b.id
    WHERE v.id = $visit_id
    LIMIT 1
");

if (!$res || $res->num_rows === 0) {
  ob_end_clean(); //clear any buffer
    die("Visit not found.");
}
$visit = $res->fetch_assoc();

// ✅ Load TCPDF

$pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);

// Document info
$pdf->SetCreator('Car Rental System');
$pdf->SetAuthor('Car Rental System');
$pdf->SetTitle('Visit Confirmation Receipt');
$pdf->SetSubject('Visit Receipt');

// Disable default header/footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

// Margins
$pdf->SetMargins(15, 15, 15);

// Add page
$pdf->AddPage();

// ✅ Build professional HTML
$html = '
<style>
    h1 { color:#0d6efd; text-align:center; }
    .header { text-align:center; border-bottom:2px solid #0d6efd; padding-bottom:10px; margin-bottom:20px; }
    .section { margin-bottom:20px; }
    table { width:100%; border-collapse: collapse; }
    th, td { padding:6px; border:1px solid #ccc; font-size:11px; }
    th { background-color:#f5f5f5; text-align:left; }
    .footer { margin-top:30px; text-align:center; font-size:10px; color:#555; }
</style>

<div class="header">
  <h1>Visit Confirmation Receipt</h1>
  <p>Receipt ID: VST-' . str_pad($visit['id'], 5, "0", STR_PAD_LEFT) . '</p>
</div>

<div class="section">
  <h3>Car Details</h3>
  <table>
    <tr><th>Brand</th><td>' . htmlspecialchars($visit['brand']) . '</td></tr>
    <tr><th>Model</th><td>' . htmlspecialchars($visit['model']) . '</td></tr>
    <tr><th>Year</th><td>' . htmlspecialchars($visit['year']) . '</td></tr>
    <tr><th>Registration No.</th><td>' . htmlspecialchars($visit['registration_no'] ?? "N/A") . '</td></tr>
  </table>
</div>

<div class="section">
  <h3>Seller Details</h3>
  <table>
    <tr><th>Name</th><td>' . htmlspecialchars($visit['seller_name']) . '</td></tr>
    <tr><th>Email</th><td>' . htmlspecialchars($visit['seller_email']) . '</td></tr>
    <tr><th>Phone</th><td>' . htmlspecialchars($visit['seller_phone'] ?? "N/A") . '</td></tr>
    <tr><th>Address</th><td>' . htmlspecialchars($visit['seller_address'] ?? "N/A") . '</td></tr>
  </table>
</div>

<div class="section">
  <h3>Buyer Details</h3>
  <table>
    <tr><th>Name</th><td>' . htmlspecialchars($visit['buyer_name']) . '</td></tr>
    <tr><th>Email</th><td>' . htmlspecialchars($visit['buyer_email']) . '</td></tr>
  </table>
</div>

<div class="section">
  <h3>Visit Information</h3>
  <table>
    <tr><th>Date & Time</th><td>' . date("M d, Y H:i", strtotime($visit['visit_date'])) . '</td></tr>
    <tr><th>Status</th><td>' . ucfirst($visit['status']) . '</td></tr>
  </table>
</div>

<div class="footer">
  <p>This receipt confirms your visit booking. Please carry this when visiting the seller.</p>
  <p>Generated by ' . (defined("APP_NAME") ? APP_NAME : "Car Rental System") . ' on ' . date("M d, Y H:i") . '</p>
</div>
';

// ✅ Write HTML into PDF
$pdf->writeHTML($html, true, false, true, false, '');
ob_end_clean(); //clear any output before sending PDF
// ✅ Output PDF
$pdf->Output("visit_receipt_$visit_id.pdf", "I"); // "I" = Inline view in browser, use "D" to force download
exit;